name: Build README

on:
  push:
    workflow_dispatch:
      schedule:
        - cron: '0 12 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Run python script
        run: python build.py
      - name: Commit and push git changes
        run: |-
          git diff
          git config --global user.email "readme-bot@example.com"
          git config --global user.name "README-bot"
          git add -A
          git commit -m "Updated content" || exit 0
          git push

